### ISSUE TITLE
Where to submit link

### ISSUE THREAD

**Issue by tarunkhatri** [Kregzo/tech_challenge#2]
Where to submit link there is no option available on LinkedIn, although i have mentioned my link in my resume and submitted on LinkedIn 10 days ago. My mail id is- khatritarun15@gmail.com

**Comment by amangsingh** [comment]
You can either submit via LinkedIn which you have.
I'll ask the HR team to forward
Alternatively, as mentioned in readme; you can create a new branch with your name. Only commits directly into main branch or pull requests into main branch are not allowed.
